### ISSUE TITLE
大佬，你分析过这个项目的结果么

### ISSUE THREAD

**Issue by darknli** [zhangfazhan/text_clustering#1]
无序属性的数据不能直接扔到聚类算法里去做，不然结果就会很奇怪，就像你这个结果一样
KMeans：{4: [0, 1, 2, 3, 4], 2: [5, 6, 7, 8, 9], 0: [10, 11, 12, 13, 14], 3: [15, 16, 17, 18, 19], 1: [20, 21, 22, 23, 24]}
Dbscan：{0: [0, 1, 2, 3, 4, 5, 6, 9, 10, 11, 12, 13, 14], -1: [7, 8, 15, 16, 17, 18, 19, 21], 1: [20, 22, 23, 24]}
完全没挖掘出数据的有价值的东西啊

**Comment by murray-z** [comment]
没懂你的无序什么意思？kmeans的结果就是正确的啊，可以看下测试数据集
